### FrameNet Testing:

In [1]:
import nltk
from nltk.corpus import framenet as fn

nltk.download("wordnet")
nltk.download("framenet_v17")

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/ricklattin/nltk_data...
[nltk_data] Downloading package framenet_v17 to
[nltk_data]     /Users/ricklattin/nltk_data...
[nltk_data]   Unzipping corpora/framenet_v17.zip.


True

In [2]:
# Function to extract frame elements from a tagged sentence
def extract_frame_elements(tagged_sentence):
    frame_elements = set()
    for word, frame_name in tagged_sentence:
        if frame_name:
            frame = fn.frame_by_name(frame_name)
            for fe in frame.FE:
                frame_elements.add(fe)
    return frame_elements

In [3]:
# Example tagged sentence
tagged_sentence = [("He", None), ("bought", "Commerce_buy"), ("a", None), ("new", None), ("car", "Commerce_buy")]

# Extract frame elements
frame_elements = extract_frame_elements(tagged_sentence)

# Print frame elements
print("Frame Elements:", frame_elements)

Frame Elements: {'Place', 'Period_of_iterations', 'Money', 'Seller', 'Goods', 'Manner', 'Recipient', 'Means', 'Purpose', 'Rate', 'Buyer', 'Time', 'Imposed_purpose', 'Unit', 'Explanation'}


### BERT Testing:

In [13]:
from transformers import BertTokenizer, TFBertModel

transfer_model_name = 'bert-base-uncased'
bert_tokenizer = BertTokenizer.from_pretrained(transfer_model_name)
bert_model = TFBertModel.from_pretrained(transfer_model_name)

# freezing all layers of bert model
for l in bert_model.bert.encoder.layer:
        l.trainable = False
bert_model.bert.embeddings.trainable = False
bert_model.bert.pooler.trainable = False


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [14]:
bert_model.summary()

Model: "tf_bert_model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
Total params: 109,482,240
Trainable params: 0
Non-trainable params: 109,482,240
_________________________________________________________________


In [15]:
# Sample sentence
sentence = "This dog is big"
sentence2 = "This dog is lovely"

# Tokenize the input sentence
inputs = bert_tokenizer([sentence, sentence2], padding=True,
return_tensors="tf")

print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 101, 2023, 3899, 2003, 2502,  102],
       [ 101, 2023, 3899, 2003, 8403,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>}
